-- Caerulea Vault
-- AK 分类第一版种子数据
-- 作用：把当前前端里已经在使用的 AK-000 ~ AK-008 导入数据库。

-- 1. 先插入记录本身。
insert into public.records (
  record_code,
  section_id,
  title,
  teaser,
  record_date,
  share_type,
  share_round_1,
  share_round_2,
  shipping,
  status,
  stage,
  notes,
  private_notes,
  total_quantity,
  advance_paid,
  remaining_stock,
  profit_loss
)
values
  (
    'AK-000',
    (select id from public.sections where code = 'AK'),
    '水月0322爱心',
    '深蓝研究所金属徽章',
    '2026-03-22',
    'count',
    5.20,
    3.22,
    5.20,
    'archived',
    'waiting_bulk',
    '水月是世界上最可爱的小水母，本车有赠送无料噢',
    '内部记录：二宣下降后需要重新核对差额。',
    120,
    560.00,
    14,
    -36.50
  ),
  (
    'AK-001',
    (select id from public.sections where code = 'AK'),
    '博士的红黄蓝小目标',
    '深蓝研究所金属徽章',
    '2026-04-01',
    'count',
    6.80,
    null,
    5.20,
    'archived',
    'draft_ready',
    '这条记录主要用于测试多物品录入、不同单价，以及点击物品名后弹出的小框。',
    '',
    null,
    null,
    null,
    null
  ),
  (
    'AK-002',
    (select id from public.sections where code = 'AK'),
    '兔兔博士QQ人',
    '深蓝研究所金属徽章',
    '2026-04-02',
    'headcount',
    7.40,
    null,
    6.00,
    'archived',
    'sampling',
    '目前已经锁车收打样，后续根据打样情况决定是否进入下一轮。',
    '',
    null,
    null,
    null,
    null
  ),
  (
    'AK-003',
    (select id from public.sections where code = 'AK'),
    '深海圆圆',
    '深蓝研究所金属徽章',
    '2026-03-10',
    'count',
    4.60,
    4.10,
    4.80,
    'archived',
    'completed',
    '该记录用于测试已归档状态与完车标签。',
    '',
    null,
    null,
    null,
    null
  ),
  (
    'AK-004',
    (select id from public.sections where code = 'AK'),
    '余圆圆',
    '深蓝研究所金属徽章',
    '2026-04-04',
    'count',
    5.90,
    null,
    5.00,
    'archived',
    'draft_ready',
    '这条主要用于测试计划重启状态的颜色和标签。',
    '',
    null,
    null,
    null,
    null
  ),
  (
    'AK-005',
    (select id from public.sections where code = 'AK'),
    '黍圆圆',
    '深蓝研究所金属徽章',
    '2026-04-07',
    'count',
    0.00,
    null,
    0.00,
    'archived',
    'draft_ready',
    '占位记录，用于承接新导入的图片素材。',
    '',
    null,
    null,
    null,
    null
  ),
  (
    'AK-006',
    (select id from public.sections where code = 'AK'),
    '净罪作战图标',
    '深蓝研究所金属徽章',
    '2026-04-07',
    'count',
    0.00,
    null,
    0.00,
    'archived',
    'draft_ready',
    '占位记录，用于承接新导入的图片素材。',
    '',
    null,
    null,
    null,
    null
  ),
  (
    'AK-007',
    (select id from public.sections where code = 'AK'),
    '相见欢蚀刻章',
    '深蓝研究所金属徽章',
    '2026-04-07',
    'count',
    0.00,
    null,
    0.00,
    'archived',
    'draft_ready',
    '占位记录，用于承接新导入的图片素材。',
    '',
    null,
    null,
    null,
    null
  ),
  (
    'AK-008',
    (select id from public.sections where code = 'AK'),
    '净罪蚀刻章',
    '深蓝研究所金属徽章',
    '2026-04-07',
    'count',
    0.00,
    null,
    0.00,
    'archived',
    'draft_ready',
    '占位记录，用于承接新导入的图片素材。',
    '',
    null,
    null,
    null,
    null
  )
on conflict (record_code) do update set
  title = excluded.title,
  teaser = excluded.teaser,
  record_date = excluded.record_date,
  share_type = excluded.share_type,
  share_round_1 = excluded.share_round_1,
  share_round_2 = excluded.share_round_2,
  shipping = excluded.shipping,
  status = excluded.status,
  stage = excluded.stage,
  notes = excluded.notes,
  private_notes = excluded.private_notes,
  total_quantity = excluded.total_quantity,
  advance_paid = excluded.advance_paid,
  remaining_stock = excluded.remaining_stock,
  profit_loss = excluded.profit_loss;

-- 2. 记录级图片。
insert into public.record_images (record_id, image_kind, label, image_path, sort_order)
values
  ((select id from public.records where record_code = 'AK-000'), 'promo', '宣图', '/archive/ak/AK-000.PNG', 0),
  ((select id from public.records where record_code = 'AK-001'), 'promo', '宣图', '/archive/ak/AK-001.PNG', 0),
  ((select id from public.records where record_code = 'AK-002'), 'promo', '宣图', '/archive/ak/AK-002.PNG', 0),
  ((select id from public.records where record_code = 'AK-003'), 'promo', '宣图', '/archive/ak/AK-003.PNG', 0),
  ((select id from public.records where record_code = 'AK-004'), 'promo', '宣图', '/archive/ak/AK-004.PNG', 0),
  ((select id from public.records where record_code = 'AK-005'), 'promo', '宣图', '/archive/ak/AK-005.PNG', 0),
  ((select id from public.records where record_code = 'AK-006'), 'promo', '宣图', '/archive/ak/AK-006.PNG', 0),
  ((select id from public.records where record_code = 'AK-007'), 'promo', '宣图', '/archive/ak/AK-007.PNG', 0),
  ((select id from public.records where record_code = 'AK-008'), 'promo', '宣图', '/archive/ak/AK-008.PNG', 0)
on conflict (record_id, image_kind, sort_order) do update set
  label = excluded.label,
  image_path = excluded.image_path;

-- 3. 物品。
insert into public.items (
  item_code,
  record_id,
  title,
  note,
  unit_price,
  image_path,
  image_fit,
  sort_order
)
values
  ('AK-000-1', (select id from public.records where record_code = 'AK-000'), '水月0322爱心金属徽章', '当前先按单物品样板展示，后续可继续补更多同团物品。', 32.20, '/archive/ak/AK-000.PNG', 'cover', 1),
  ('AK-001-1', (select id from public.records where record_code = 'AK-001'), '合成玉镀黑ffl', 'ffl 系列，默认单独展示。', 12.00, '/archive/ak/AK-001.PNG', 'contain', 1),
  ('AK-001-2', (select id from public.records where record_code = 'AK-001'), '源石镀黑ffl', 'ffl 系列，默认单独展示。', 12.00, null, 'cover', 2),
  ('AK-001-3', (select id from public.records where record_code = 'AK-001'), '龙门币镀黑ffl', 'ffl 系列，默认单独展示。', 12.00, null, 'cover', 3),
  ('AK-001-4', (select id from public.records where record_code = 'AK-001'), '合成玉镀玫瑰金ffl', 'ffl 系列，默认单独展示。', 12.00, null, 'cover', 4),
  ('AK-001-5', (select id from public.records where record_code = 'AK-001'), '源石镀金ffl', 'ffl 系列，默认单独展示。', 12.00, null, 'cover', 5),
  ('AK-001-6', (select id from public.records where record_code = 'AK-001'), '龙门币镀银ffl', 'ffl 系列，默认单独展示。', 12.00, null, 'cover', 6),
  ('AK-001-7', (select id from public.records where record_code = 'AK-001'), '合成玉镀黑kq', 'kq 系列，默认单独展示。', 10.00, null, 'cover', 7),
  ('AK-001-8', (select id from public.records where record_code = 'AK-001'), '源石镀黑kq', 'kq 系列，默认单独展示。', 10.00, null, 'cover', 8),
  ('AK-001-9', (select id from public.records where record_code = 'AK-001'), '龙门币镀黑kq', 'kq 系列，默认单独展示。', 10.00, null, 'cover', 9),
  ('AK-001-10', (select id from public.records where record_code = 'AK-001'), '合成玉镀玫瑰金kq', 'kq 系列，默认单独展示。', 10.00, null, 'cover', 10),
  ('AK-001-11', (select id from public.records where record_code = 'AK-001'), '源石镀金kq', 'kq 系列，默认单独展示。', 10.00, null, 'cover', 11),
  ('AK-001-12', (select id from public.records where record_code = 'AK-001'), '龙门币镀银kq', 'kq 系列，默认单独展示。', 10.00, null, 'cover', 12),
  ('AK-001-13', (select id from public.records where record_code = 'AK-001'), '特典：合成玉喷红kq', '特典条目。', 6.00, null, 'cover', 13),
  ('AK-001-14', (select id from public.records where record_code = 'AK-001'), '特典：源石喷橙kq', '特典条目。', 6.00, null, 'cover', 14),
  ('AK-001-15', (select id from public.records where record_code = 'AK-001'), '特典：龙门币喷蓝kq', '特典条目。', 6.00, null, 'cover', 15),
  ('AK-002-1', (select id from public.records where record_code = 'AK-002'), '兔兔博士QQ人金属徽章', '用于测试研究中但不同小阶段的标签效果。', 30.00, '/archive/ak/AK-002.PNG', 'contain', 1),
  ('AK-003-1', (select id from public.records where record_code = 'AK-003'), '深海圆圆金属徽章', '用于测试归档状态展示。', 26.00, '/archive/ak/AK-003.PNG', 'cover', 1),
  ('AK-004-1', (select id from public.records where record_code = 'AK-004'), '余圆圆金属徽章', '用于测试计划重启状态展示。', 29.90, '/archive/ak/AK-004.PNG', 'cover', 1),
  ('AK-005-1', (select id from public.records where record_code = 'AK-005'), '黍圆圆金属徽章', '等待补充具体物品信息。', 0.00, '/archive/ak/AK-005.PNG', 'cover', 1),
  ('AK-006-1', (select id from public.records where record_code = 'AK-006'), '净罪作战图标金属徽章', '等待补充具体物品信息。', 0.00, '/archive/ak/AK-006.PNG', 'cover', 1),
  ('AK-007-1', (select id from public.records where record_code = 'AK-007'), '相见欢蚀刻章金属徽章', '等待补充具体物品信息。', 0.00, '/archive/ak/AK-007.PNG', 'cover', 1),
  ('AK-008-1', (select id from public.records where record_code = 'AK-008'), '净罪蚀刻章金属徽章', '等待补充具体物品信息。', 0.00, '/archive/ak/AK-008.PNG', 'cover', 1)
on conflict (item_code) do update set
  title = excluded.title,
  note = excluded.note,
  unit_price = excluded.unit_price,
  image_path = excluded.image_path,
  image_fit = excluded.image_fit,
  sort_order = excluded.sort_order;

-- 4. 标签总表。
insert into public.tags (name, slug, tag_type)
values
  ('研究中-等大货', 'active-waiting-bulk', 'status'),
  ('未展开研究-已出稿', 'planned-draft-ready', 'status'),
  ('研究中-打样', 'active-sampling', 'status'),
  ('已归档-完车', 'archived-completed', 'status'),
  ('计划重启', 'restart-planned', 'status'),
  ('待整理', 'to-sort', 'status'),
  ('水月', 'mizuki', 'character'),
  ('博士', 'doctor', 'character'),
  ('W', 'w', 'character'),
  ('陈', 'chen', 'character'),
  ('艾雅法拉', 'eyjafjalla', 'character'),
  ('金属徽章', 'metal-pin', 'generic'),
  ('爱心', 'heart', 'generic'),
  ('ffl', 'ffl', 'generic'),
  ('kq', 'kq', 'generic'),
  ('特典', 'bonus', 'generic'),
  ('合成玉', 'originium-prime-chip', 'generic'),
  ('源石', 'originium', 'generic'),
  ('龙门币', 'lungmen-coin', 'generic'),
  ('打样中', 'sampling', 'generic'),
  ('完车', 'completed', 'generic'),
  ('二开预备', 'restart-prep', 'generic')
on conflict (name) do nothing;

-- 5. 记录标签关系。
insert into public.record_tags (record_id, tag_id)
select r.id, t.id
from (
  values
    ('AK-000', '研究中-等大货'),
    ('AK-000', '水月'),
    ('AK-001', '未展开研究-已出稿'),
    ('AK-001', '金属徽章'),
    ('AK-001', '博士'),
    ('AK-002', '研究中-打样'),
    ('AK-002', '金属徽章'),
    ('AK-002', 'W'),
    ('AK-003', '已归档-完车'),
    ('AK-003', '金属徽章'),
    ('AK-003', '陈'),
    ('AK-004', '计划重启'),
    ('AK-004', '金属徽章'),
    ('AK-004', '艾雅法拉'),
    ('AK-005', '待整理'),
    ('AK-005', '金属徽章'),
    ('AK-006', '待整理'),
    ('AK-006', '金属徽章'),
    ('AK-007', '待整理'),
    ('AK-007', '金属徽章'),
    ('AK-008', '待整理'),
    ('AK-008', '金属徽章')
) as x(record_code, tag_name)
join public.records r on r.record_code = x.record_code
join public.tags t on t.name = x.tag_name
on conflict do nothing;

-- 6. 物品标签关系。
insert into public.item_tags (item_id, tag_id)
select i.id, t.id
from (
  values
    ('AK-000-1', '水月'),
    ('AK-000-1', '爱心'),
    ('AK-000-1', '金属徽章'),
    ('AK-001-1', '博士'),
    ('AK-001-1', 'ffl'),
    ('AK-001-1', '合成玉'),
    ('AK-001-2', '博士'),
    ('AK-001-2', 'ffl'),
    ('AK-001-2', '源石'),
    ('AK-001-3', '博士'),
    ('AK-001-3', 'ffl'),
    ('AK-001-3', '龙门币'),
    ('AK-001-4', '博士'),
    ('AK-001-4', 'ffl'),
    ('AK-001-4', '合成玉'),
    ('AK-001-5', '博士'),
    ('AK-001-5', 'ffl'),
    ('AK-001-5', '源石'),
    ('AK-001-6', '博士'),
    ('AK-001-6', 'ffl'),
    ('AK-001-6', '龙门币'),
    ('AK-001-7', '博士'),
    ('AK-001-7', 'kq'),
    ('AK-001-7', '合成玉'),
    ('AK-001-8', '博士'),
    ('AK-001-8', 'kq'),
    ('AK-001-8', '源石'),
    ('AK-001-9', '博士'),
    ('AK-001-9', 'kq'),
    ('AK-001-9', '龙门币'),
    ('AK-001-10', '博士'),
    ('AK-001-10', 'kq'),
    ('AK-001-10', '合成玉'),
    ('AK-001-11', '博士'),
    ('AK-001-11', 'kq'),
    ('AK-001-11', '源石'),
    ('AK-001-12', '博士'),
    ('AK-001-12', 'kq'),
    ('AK-001-12', '龙门币'),
    ('AK-001-13', '特典'),
    ('AK-001-13', 'kq'),
    ('AK-001-13', '合成玉'),
    ('AK-001-14', '特典'),
    ('AK-001-14', 'kq'),
    ('AK-001-14', '源石'),
    ('AK-001-15', '特典'),
    ('AK-001-15', 'kq'),
    ('AK-001-15', '龙门币'),
    ('AK-002-1', 'W'),
    ('AK-002-1', '金属徽章'),
    ('AK-002-1', '打样中'),
    ('AK-003-1', '陈'),
    ('AK-003-1', '金属徽章'),
    ('AK-003-1', '完车'),
    ('AK-004-1', '艾雅法拉'),
    ('AK-004-1', '金属徽章'),
    ('AK-004-1', '二开预备'),
    ('AK-005-1', '待整理'),
    ('AK-006-1', '待整理'),
    ('AK-007-1', '待整理'),
    ('AK-008-1', '待整理')
) as x(item_code, tag_name)
join public.items i on i.item_code = x.item_code
join public.tags t on t.name = x.tag_name
on conflict do nothing;
